### PR TITLE
Release v1.14.0

### PR DESCRIPTION
**Pull request by alexmalins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Update dependencies
- Use conda-forge/harlequin maintainers handle
- Add alexmalins as maintainer

### CODE REVIEW

**Comment by alexmalins** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — CHANGES_REQUESTED** [review]
No, this will break the maintenance team.

**Comment by xhochy** [comment]
I would rather merge https://github.com/conda-forge/harlequin-feedstock/pull/30 as this is already ready. The downstream dependency needs to be fixed.

**Comment by alexmalins** [comment]
> I would rather merge #30 as this is already ready. The downstream dependency needs to be fixed.

no problem thank you!

**Pull request closed without merging**
